services:
  mongodb:
    image: mongo:8.0.1
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
  backend:
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "3001:3001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=ceddyboi
    depends_on:
      - mongodb  
    env_file:
      - path: ./backend/.env
        required: true
  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "5173:5173"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - path: ./frontend/.env
        required: true
volumes:
  mongodb-data:
    driver: local

networks:
  nginx-proxy-manager_nginx:
    driver: bridge
    external: true