runtime: nodejs16 # or another supported version

env_variables:
    MONGO_URL: "mongodb+srv://Cedric0303:Chen8802@cluster0.inzj8j9.mongodb.net/lendela?retryWrites=true&w=majority"

handlers:
    - url: /.*
      secure: always
      redirect_http_response_code: 301
      script: auto
